name: amabnb

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: gradle build
        run: ./gradlew build

      - name: jar 파일 복사
        run: cp ./build/libs/amabnb-1.0.1.jar ./deploy

      - name: 도커 빌드 및 푸쉬
        working-directory: ./deploy
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ secrets.DOCKER_TAG_DEV }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ secrets.DOCKER_TAG_DEV }}

      - name: 도커용 .env file 생성
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          envkey_DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          envkey_DOCKER_TAG_DEV: ${{ secrets.DOCKER_TAG_DEV }}
          directory: ./deploy
          file_name: .env

      - name: 스프링 .env file 생성
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_URL: ${{ secrets.DB_URL }}
          envkey_DB_USER_NAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          envkey_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          directory: ./deploy
          file_name: spring.env

      - name: EC2 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./deploy/*"
          target: "/home/ec2-user/test"
          strip_components: 1

      - name: EC2 배포 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/test
            bash deploy.sh \
            ${{ secrets.DOCKER_USERNAME }} \
            ${{ secrets.DOCKER_REPOSITORY }} \
            ${{ secrets.DOCKER_TAG_DEV }}
####
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./build/reports/jacoco/test/jacocoTestReport.xml

